import { SessionDefinition } from '../audio/types';

export const PRESETS: SessionDefinition[] = [
  {
    id: 'relaxation',
    name: 'Relaxation / Orientation',
    description: 'Alpha range entrainment for calm orientation and resonant tuning',
    targetBand: 'Alpha (8–12 Hz)',
    affirmations: [
      'I am calm, centered, and open to inner guidance.',
      'My mind and body relax into perfect harmony.',
      'I am more than my physical body.',
      'Peace flows through me with every breath.',
      'I am ready to explore expanded awareness.',
    ],
    phases: [
      {
        label: 'Induction',
        durationSec: 300,
        beatHzStart: 8,
        beatHzEnd: 10,
        alternatorBlend: 0.4,
        baseCarrierHz: 100,
        breathingPattern: '4-7-8',
        affirmation: 'Allow your body to relax completely.',
      },
      {
        label: 'Alpha Plateau',
        durationSec: 600,
        beatHzStart: 10,
        beatHzEnd: 12,
        alternatorBlend: 0.5,
        baseCarrierHz: 110,
        breathingPattern: '4-7-8',
        affirmation: 'You are entering a state of relaxed alertness.',
      },
      {
        label: 'Resonant Tuning',
        durationSec: 300,
        beatHzStart: 12,
        beatHzEnd: 10,
        alternatorBlend: 0.3,
        baseCarrierHz: 100,
        breathingPattern: 'box',
        affirmation: 'Feel the resonance aligning your energy.',
      },
      {
        label: 'Return',
        durationSec: 300,
        beatHzStart: 10,
        beatHzEnd: 8,
        alternatorBlend: 0.2,
        baseCarrierHz: 90,
        breathingPattern: 'box',
        affirmation: 'Gently return, carrying this peace with you.',
      },
    ],
  },
  {
    id: 'deepening',
    name: 'Deepening (Focus 10/12)',
    description: 'Theta entrainment for body asleep, mind awake — profound inner focus',
    targetBand: 'Theta (4–8 Hz)',
    affirmations: [
      'My body sleeps while my mind remains alert and aware.',
      'I am safe to explore the depths of consciousness.',
      'Each breath takes me deeper into stillness.',
      'I access wisdom beyond ordinary perception.',
      'The gateway opens within me.',
    ],
    phases: [
      {
        label: 'Descent',
        durationSec: 420,
        beatHzStart: 8,
        beatHzEnd: 6,
        alternatorBlend: 0.5,
        baseCarrierHz: 100,
        breathingPattern: '4-7-8',
        affirmation: 'Begin your descent into deep relaxation.',
      },
      {
        label: 'Theta Threshold',
        durationSec: 480,
        beatHzStart: 6,
        beatHzEnd: 5,
        alternatorBlend: 0.6,
        baseCarrierHz: 105,
        breathingPattern: '4-7-8',
        affirmation: 'Your body grows heavy; your mind stays lucid.',
      },
      {
        label: 'Focus 10 Plateau',
        durationSec: 600,
        beatHzStart: 5,
        beatHzEnd: 4,
        alternatorBlend: 0.5,
        baseCarrierHz: 100,
        breathingPattern: null,
        affirmation: 'You have reached Focus 10. Rest in this space.',
      },
      {
        label: 'Focus 12 Deepening',
        durationSec: 300,
        beatHzStart: 4,
        beatHzEnd: 4.5,
        alternatorBlend: 0.4,
        baseCarrierHz: 95,
        breathingPattern: null,
        affirmation: 'Deeper still. The inner gateway awaits.',
      },
      {
        label: 'Gentle Return',
        durationSec: 300,
        beatHzStart: 4.5,
        beatHzEnd: 8,
        alternatorBlend: 0.3,
        baseCarrierHz: 100,
        breathingPattern: 'box',
        affirmation: 'Slowly rise, integrating your experience.',
      },
    ],
  },
  {
    id: 'exploration',
    name: 'Exploration / Psychic',
    description: 'Gradual ramp through theta into beta/gamma for expanded perception',
    targetBand: 'Theta → Beta → Gamma',
    affirmations: [
      'I expand beyond the limits of ordinary perception.',
      'Higher frequencies of consciousness are available to me.',
      'I perceive energy and information beyond the physical.',
      'My psychic senses awaken naturally and safely.',
      'I am a channel for universal wisdom.',
      'Coherence and clarity guide my exploration.',
    ],
    phases: [
      {
        label: 'Theta Induction',
        durationSec: 360,
        beatHzStart: 6,
        beatHzEnd: 4,
        alternatorBlend: 0.5,
        baseCarrierHz: 100,
        breathingPattern: '4-7-8',
        affirmation: 'Settle into theta — the gateway frequency.',
      },
      {
        label: 'Energy Buildup',
        durationSec: 300,
        beatHzStart: 4,
        beatHzEnd: 8,
        alternatorBlend: 0.6,
        baseCarrierHz: 120,
        breathingPattern: 'box',
        affirmation: 'Feel energy gathering at your crown.',
      },
      {
        label: 'Beta Ramp',
        durationSec: 360,
        beatHzStart: 8,
        beatHzEnd: 20,
        alternatorBlend: 0.7,
        baseCarrierHz: 140,
        breathingPattern: null,
        affirmation: 'Rising into expanded awareness.',
      },
      {
        label: 'Gamma Burst',
        durationSec: 240,
        beatHzStart: 20,
        beatHzEnd: 40,
        alternatorBlend: 0.8,
        baseCarrierHz: 160,
        breathingPattern: null,
        affirmation: 'Peak coherence. Perceive without limits.',
      },
      {
        label: 'Integration',
        durationSec: 300,
        beatHzStart: 40,
        beatHzEnd: 10,
        alternatorBlend: 0.4,
        baseCarrierHz: 110,
        breathingPattern: 'box',
        affirmation: 'Integrate your experience with gratitude.',
      },
      {
        label: 'Cooldown',
        durationSec: 240,
        beatHzStart: 10,
        beatHzEnd: 6,
        alternatorBlend: 0.3,
        baseCarrierHz: 100,
        breathingPattern: '4-7-8',
        affirmation: 'Return gently to ordinary awareness.',
      },
    ],
  },
];

export const CUSTOM_PRESET: SessionDefinition = {
  id: 'custom',
  name: 'Custom',
  description: 'Manual control — set your own frequencies and explore freely',
  targetBand: 'User-defined',
  affirmations: [
    'I am the architect of my inner experience.',
    'Sound guides me to my center.',
    'I trust the wisdom of my own consciousness.',
  ],
  phases: [],
};

export function getPresetById(id: string): SessionDefinition {
  return PRESETS.find((p) => p.id === id) ?? CUSTOM_PRESET;
}

export function getTotalDuration(preset: SessionDefinition): number {
  return preset.phases.reduce((sum, phase) => sum + phase.durationSec, 0);
}
